config/routes.rb
Rails.application.routes.draw do
  root :to => 'passthrough#index'
  get 'home', to:"pages#home"
  get "styleguide", to: "pages#stylguide"
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  resources :teams, only: [:new, :create, :index, :show, :update] do
    get 'overview', to: 'dashboards#overview'
    get 'proposals', to: 'dashboards#proposals'
    get 'projects', to: 'dashboards#projects'
    resources :proposals, only: [:new, :create, :update, :edit, :show] do
      get 'accepted', to: 'proposals#accepted'
      get 'declined', to: 'proposals#declined'
    end
  end
  resources :deliverables, only: [:create]
  resources :clients, only: [:create]

  post '/invitation', to: 'invitations#create', as: :invitations
  resources :users do
    get 'overview', to: 'dashboards#overview_user'
  end

  resources :projects, only: [:new, :create, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © Moonstra 2021, all rights reserved
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-black.png"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Teams", teams_path, class: "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "About", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_team_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="side-bar">
  <div class="side-bar-header">
    <%= cl_image_tag current_user.photo.key, height: 100, width: 100, crop: :fill %>
    <p>Username: <%= current_user.username %></p>
    <p>

    <% if current_user.team.nil? %>
    <ul style="list-style: none; padding: 0px">
      <li><%= link_to "Find projects", projects_path %></li>
      <li><%= link_to "Post services in marketplace" %></li>
    </ul>
    <% else %>
      <strong>
        <%= current_user.team.name %>
      </strong>
      </p>
      <ul style="list-style: none;">
        <li> <%= link_to "Overview", root_path(@team) %> </li>
        <li> <%= link_to "Proposals", team_proposals_path(@team) %> </li>
        <li> <%= link_to "Projects", team_projects_path(@team) %> </li>
        <li> <%= link_to "Clients", team_proposals_path(@team) %> </li>
        <li> <%= link_to "Profile", edit_user_registration_path(@team) %> </li>
      </ul>
      <%= link_to "Find projects", projects_path %>
      <%= link_to "Create project", new_project_path %>
    <% end %>

  </div>
</div>