config/routes.rb
Rails.application.routes.draw do
  root :to => 'passthrough#index'
  get 'home', to:"pages#home"
  get "styleguide", to: "pages#stylguide"
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  resources :teams, only: [:new, :create, :index, :show, :update] do
    get 'overview', to: 'dashboards#overview'
    get 'proposals', to: 'dashboards#proposals'
    get 'projects', to: 'dashboards#projects'
    resources :proposals, only: [:new, :create, :update, :edit, :show] do
      get 'accepted', to: 'proposals#accepted'
      get 'declined', to: 'proposals#declined'
    end
  end
  resources :deliverables, only: [:create]
  resources :clients, only: [:create]

  post '/invitation', to: 'invitations#create', as: :invitations
  resources :users do
    get 'overview', to: 'dashboards#overview_user'
  end

  resources :projects, only: [:new, :create, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_policy_scoped
  before_action :set_team, only: [:overview, :find_team_projects, :proposals, :projects]
  before_action :set_team_projects, only: [:overview, :proposals, :projects]

  def overview
    @last_projects = TeamsProject.where(team_id: current_user.team).order("updated_at DESC").limit(5)
    @last_proposals = Proposal.where(teams_project: TeamsProject.where(team:current_user.team)).order("updated_at DESC").limit(5)
  end

  def proposals
    @user_projects = ProjectMember.where(user: current_user)
  end

  def projects
    @user_projects = ProjectMember.where(user: current_user)
  end

  def overview_user

  end

  private

  def set_team
    if params[:team_id]
      @team = Team.find(params[:team_id])
    end
  end

  def set_team_projects
    if params[:team_id]
      @teams_projects = @team.teams_projects
    end
  end
end

app/views/dashboards/overview.html.erb
<div class="small-card">
  <%= @team.name %>
</div>


<h2>Last updated team projects</h2>
<div class="small-card p-3" style="border-radius: 10px">
  <ul style="list-style-type: none">
    <% @last_projects.each do |last_project| %>
      <li> <%= last_project.project.name %> </li>
      <% if last_project.status == "pending" %>
        <p style="background-color:red"><%= last_project.status %></p>
      <% end %>
      <% last_project.project_members.each do |member| %>
        <p> <%= member.user.first_name %> </p>
      <% end %>
    <% end %>
  </ul>
</div>
<h2>Last proposals</h2>
<div class="big-card">
  <ul style="list-style:none">
    <% @last_proposals.each do |last_proposal| %>
      <li>
        <div class="d-flex flex-column">
          <%= last_proposal.title %>
          <%= last_proposal.teams_project.project.name %> -
          <%= last_proposal.client.company_name %>
        </div>
        <%= last_proposal.status %> - <%= last_proposal.total_price %> €
      </li>
    <% end %>
  </ul>
</div>

<h2>Team's categories</h2>



<%= link_to "Profile", edit_user_registration_path %>

app/views/dashboards/overview_user.html.erb
<h1>Welcome back, <%= current_user.first_name %></h1>

app/views/dashboards/projects.html.erb
  <ul class="nav mb-3 nav-tabs" id="project-tab" role="tablist">
    <li class="nav-item dashboard-nav">
      <a class="nav-link active" id="yours-tab" data-toggle="pill" href="#yours" role="tab" aria-controls="yours" aria-selected="true">Yours</a>
    </li>
    <li class="nav-item dashboard-nav" id="project-tab">
      <a class="nav-link" id="teams-tab" data-toggle="pill" href="#teams" role="tab" aria-controls="teams" aria-selected="false">Team</a>
    </li>
  </ul>

  <div class="tab-content" id="project-tabContent">
    <div class="tab-pane fade show active" id="yours" role="tabpanel" aria-labelledby="yours-tab">
      <div class="big-card">
        <ul style="list-style:none">
          <% @user_projects.each do |users_project| %>
              <%= users_project.teams_project.project.name %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="tab-pane fade" id="teams" role="tabpanel" aria-labelledby="teams-tab">
      <div class="big-card">
        <ul style="list-style:none">
          <% @teams_projects.each do |teams_project| %>
            <%= teams_project.project.name %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

app/views/dashboards/proposals.html.erb
<%= link_to "new proposal", new_team_proposal_path(@team) %>

  <ul class="nav mb-3 nav-tabs" id="proposal-tab" role="tablist">
    <li class="nav-item dashboard-nav">
      <a class="nav-link active" id="yours-tab" data-toggle="pill" href="#yours" role="tab" aria-controls="yours" aria-selected="true">Yours</a>
    </li>
    <li class="nav-item dashboard-nav" id="proposal-tab">
      <a class="nav-link" id="teams-tab" data-toggle="pill" href="#teams" role="tab" aria-controls="teams" aria-selected="false">Team</a>
    </li>
  </ul>

  <div class="tab-content" id="proposal-tabContent">
    <div class="tab-pane fade show active" id="yours" role="tabpanel" aria-labelledby="yours-tab">
      <div class="big-card">
        <ul style="list-style:none">
          <% @user_projects.each do |user_project| %>
              <% user_project.teams_project.proposals.each do |proposal| %>
                <li>
                  <div class="d-flex flex-column">
                    <%= proposal.title %>
                    <%= proposal.teams_project.project.name %> -
                    <%= proposal.client.company_name %>
                  </div>
                   - <%= proposal.total_price %> €
                  <%= proposal.status %>
                  <%= link_to team_proposal_accepted_path(@team, proposal) do %>
                    <i class="fas fa-check-circle"></i>
                  <% end %>
                  <%= link_to team_proposal_declined_path(@team, proposal) do %>
                    <i class="fas fa-times-circle"></i>
                  <% end %>
                </li>
              <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="tab-pane fade" id="teams" role="tabpanel" aria-labelledby="teams-tab">
      <div class="big-card">
        <ul style="list-style:none">
          <% @teams_projects.each do |teams_project| %>
              <% teams_project.proposals.each do |proposal| %>
                <li>
                  <div class="d-flex flex-column">
                    <%= proposal.title %>
                    <%= proposal.teams_project.project.name %> -
                    <%= proposal.client.company_name %>
                  </div>
                  <%= proposal.status %> - <%= proposal.total_price %> €
                </li>
              <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>